//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eportafolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public string linkedin { get; set; }
        public string website { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Skills { get; set; }
        public string Tools { get; set; }
    }
}
